language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11.10.1"
script:
  - npm run check:src
  - npm run build
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.npm
after_success: npm run test:cov
